import React, { useState } from 'react';
import { db } from '../firebase';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import Spinner from './Spinner';

type FirebaseUser = {
  uid: string;
  email: string | null;
};

interface FeedbackModalProps {
  isOpen: boolean;
  onClose: () => void;
  user: FirebaseUser | null;
}

const questions = [
  { id: 'q1_chatbot', text: "How satisfied are you with the Chatbot's responsiveness and accuracy?" },
  { id: 'q2_imageGen', text: 'How would you rate the quality of the images generated by the Image Generator?' },
  { id: 'q3_imageAnalyzer', text: 'How useful did you find the Image Analyzer feature?' },
  { id: 'q4_videoGen', text: 'How satisfied are you with the quality and speed of the Video Generator?' },
  { id: 'q5_liveAgent', text: 'What is your opinion on the real-time performance of the Live Conversation Agent?' },
  { id: 'q6_groundedSearch', text: 'How accurate and helpful is the Grounded Search feature?' },
  { id: 'q7_ui', text: "How easy is it to navigate and use the application's user interface (UI)?" },
  { id: 'q8_performance', text: 'How would you rate the overall performance and speed of the app?' },
  { id: 'q9_recommend', text: 'How likely are you to recommend NexaNeuron to a friend or colleague?' },
];

const options = ['Very Dissatisfied', 'Dissatisfied', 'Neutral', 'Satisfied', 'Very Satisfied'];

const XCircleIcon: React.FC<{ className?: string }> = ({ className = "w-5 h-5" }) => (
    <svg className={className} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
);

const FeedbackModal: React.FC<FeedbackModalProps> = ({ isOpen, onClose, user }) => {
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [comments, setComments] = useState('');
  const [loading, setLoading] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState('');

  const handleOptionChange = (questionId: string, value: string) => {
    setAnswers(prev => ({ ...prev, [questionId]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) {
      setError("You must be logged in to submit feedback.");
      return;
    }
    if (Object.keys(answers).length < questions.length) {
        setError("Please answer all multiple-choice questions.");
        return;
    }

    setLoading(true);
    setError('');

    try {
      await addDoc(collection(db, 'feedback'), {
        userId: user.uid,
        userEmail: user.email,
        submittedAt: serverTimestamp(),
        ...answers,
        q10_comments: comments,
      });
      setSubmitted(true);
    } catch (err) {
      console.error("Error submitting feedback:", err);
      setError("Failed to submit feedback. Please try again later.");
    } finally {
      setLoading(false);
    }
  };
  
  const handleClose = () => {
    setAnswers({});
    setComments('');
    setSubmitted(false);
    setError('');
    onClose();
  }

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-gray-900/80 backdrop-blur-sm flex items-center justify-center z-50 p-4" onClick={handleClose}>
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col animate-fade-in-down" onClick={e => e.stopPropagation()}>
        <div className="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700 flex-shrink-0">
          <h2 className="text-xl font-bold text-gray-900 dark:text-white">Share Your Feedback</h2>
          <button onClick={handleClose} className="p-1 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-500 dark:text-gray-400">
            <XCircleIcon className="w-6 h-6" />
          </button>
        </div>
        
        <div className="p-6 overflow-y-auto flex-1">
          {submitted ? (
            <div className="text-center py-10">
                <svg className="w-16 h-16 text-green-500 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
              <h3 className="text-2xl font-bold text-gray-900 dark:text-white">Thank You!</h3>
              <p className="text-gray-600 dark:text-gray-300 mt-2">Your feedback has been submitted successfully.</p>
              <button onClick={handleClose} className="mt-6 px-6 py-2 bg-indigo-600 text-white font-semibold rounded-full hover:bg-indigo-700 transition-colors">
                Close
              </button>
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-6">
              {questions.map((q, index) => (
                <div key={q.id}>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">{index + 1}. {q.text}</label>
                  <div className="mt-2 flex flex-wrap gap-x-4 gap-y-2">
                    {options.map(option => (
                      <label key={option} className="flex items-center space-x-2 text-sm text-gray-600 dark:text-gray-400">
                        <input
                          type="radio"
                          name={q.id}
                          value={option}
                          checked={answers[q.id] === option}
                          onChange={() => handleOptionChange(q.id, option)}
                          className="form-radio h-4 w-4 text-indigo-600 bg-gray-200 dark:bg-gray-900 border-gray-300 dark:border-gray-600 focus:ring-indigo-500"
                        />
                        <span>{option}</span>
                      </label>
                    ))}
                  </div>
                </div>
              ))}
              <div>
                <label htmlFor="comments" className="block text-sm font-medium text-gray-700 dark:text-gray-300">10. Do you have any additional comments or suggestions for improvement?</label>
                <textarea
                  id="comments"
                  value={comments}
                  onChange={(e) => setComments(e.target.value)}
                  rows={4}
                  className="mt-1 block w-full bg-gray-100 dark:bg-gray-900 border-gray-300 dark:border-gray-600 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm text-gray-900 dark:text-white"
                  placeholder="Your thoughts..."
                />
              </div>
              {error && <p className="text-sm text-red-500 dark:text-red-400">{error}</p>}
            </form>
          )}
        </div>
        
        {!submitted && (
            <div className="flex-shrink-0 p-4 border-t border-gray-200 dark:border-gray-700 flex justify-end gap-4">
            <button type="button" onClick={handleClose} className="px-4 py-2 text-sm font-medium text-gray-700 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-full hover:bg-gray-50 dark:hover:bg-gray-700">Cancel</button>
            <button
                type="submit"
                onClick={handleSubmit}
                disabled={loading}
                className="px-6 py-2 flex items-center justify-center gap-2 bg-gradient-to-br from-indigo-500 to-purple-600 text-white font-semibold rounded-full shadow-lg ring-1 ring-white/20 transition-all duration-300 ease-in-out transform hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed"
            >
                {loading ? <Spinner size="sm"/> : 'Submit Feedback'}
            </button>
            </div>
        )}
      </div>
    </div>
  );
};

export default FeedbackModal;